### ISSUE TITLE
Possible problem with starter template version targeting.

### ISSUE THREAD

**Issue by mmunnis** [aspnetboilerplate/module-zero-template#104]
It appears some of the project reference targeting may be off for MVC5.x + AngularJS/MPA + ModuleZero starter templates (generated via web).

Latest Stable generates a web project targeting Abp 3.1.1, while other projects (core, app) target Abp 3.1.0.  It extracts to a folder /3.1.1

Pre-Release generates all projects targeting 3.1.0, but the project extracts to a folder called /3.1.1.

**Comment by hikalkan** [comment]
Thank you for reporting. We will check this.
However, template versions and framework versions may be different, that's normal.

**Comment by alirizaadiyahsi** [comment]
It is fixed in this commit : https://github.com/aspnetboilerplate/module-zero-template/commit/3a1322594bf9a2d1cc1711a83e058b0311c5d057
