### ISSUE TITLE
material icons do not work on IE11

### ISSUE THREAD

**Issue by gpcaretti** [aspnetboilerplate/module-zero-template#110]
* ABP 3.2.5
* module-zero-template v3.1.3

Material icons are not visible on IE11 with [self hosting icons](http://google.github.io/material-design-icons/#setup-method-2-self-hosting). It works using them via [google web font](http://google.github.io/material-design-icons/#setup-method-1-using-via-google-web-fonts):

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

Please, find attached:

1. screenshot of how layout appears with the official release of _Layout.cshtml
2. modified _Layout.cshtml and BundleConfig.cs
3. screenshot of how layout appears with the modified _Layout.cshtml and BundleConfig.cs

![capture_original](https://user-images.githubusercontent.com/5499871/33443967-3737c130-d5f9-11e7-8590-1f001975ef9d.PNG)
[_Layout.zip](https://github.com/aspnetboilerplate/module-zero-template/files/1518748/_Layout.zip)
![capture_fixed](https://user-images.githubusercontent.com/5499871/33443994-48e81bd2-d5f9-11e7-9c93-04657babf61b.PNG)

**Comment by hikalkan** [comment]
Thank you @gpcaretti 
We use self hosting since you may want to develop an intranet application that can not access to the internet.

It would be good if someone sends a PR for that. We think it would be good to use it from googleapis.com and fallback to local when not available.
