### ISSUE TITLE
 MVC application forgets the roles of an user while editing it

### ISSUE THREAD

**Issue by gpcaretti** [aspnetboilerplate/module-zero-template#112]
In the MVC application, when you try to edit an user, the form does not remember the original roles assigned to the user, if `role.DisplaName` and `role.Name` are different.

[Here](https://github.com/gpcaretti/module-zero-template/commit/b8d6e1bdf4e175915b8033efc07c534b0d324ed1) a fix of `EditUserModalViewModel.cs` that use use  `role.Name` .

**Comment by ismcagdas** [comment]
@gpcaretti I couldn't reproduce it on the latest version.
Latest version uses NormalizedName, https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Models/Users/EditUserModalViewModel.cs#L16

**Comment by Ivangrasp** [comment]
@ismcagdas That's a different repo. https://github.com/aspnetboilerplate/module-zero-template/blob/master/src/AbpCompanyName.AbpProjectName.WebMpa/Models/Users/EditUserModalViewModel.cs

**Comment by ismcagdas** [comment]
Thanks a lot @gpcaretti @Ivangrasp
