### ISSUE TITLE
Missing files and changes in downloaded template.

### ISSUE THREAD

**Issue by Ivangrasp** [aspnetboilerplate/module-zero-template#118]
I noticed that version 3.2.0 downloaded from [here](https://aspnetboilerplate.com/Templates) (MVC 5.x) doesn't contain ```Web\lib\abp-web-resources``` folder.

Also, in version 3.1.4, the file ```Web\lib\abp-web-resources\Abp\Framework\scripts\libs\abp.jquery,js``` doesn't include the changes done [here](https://github.com/aspnetboilerplate/aspnetboilerplate/commit/535e2eadf5d7e6083d64a1f817d8fc2bdb553b72). I don't know if that's the only case or if all the ```Web\lib\abp-web-resources``` isn't updated to ABP 3.3.0

**Comment by Ivangrasp** [comment]
I'm confused now. The correct files are in the ```Abp``` folder and they're updated to the respective ABP, as far as I can tell, but all the references in the ```Web\App_Start\BundleConfig.cs``` files are pointed to the ```lib``` instead.

There are some new files in the ```Content```  folder, related to bootstrap, but the references mentioned earlier point to ```lib```. Bootstrap is also located in the ```Scripts``` folder.

Which are the correct references for bootstrap, jquery, signalr, moments, etc.? Because they're also in the ```lib``` folder and everything in ```Web\App_Start\BundleConfig.cs``` points to them.

**Comment by ismcagdas** [comment]
@Ivangrasp this must be fixed in latest version https://github.com/aspnetboilerplate/module-zero-template/blob/master/src/AbpCompanyName.AbpProjectName.WebMpa/App_Start/BundleConfig.cs#L40-L45.

As far as I remember "Abp.Web.Resources" nuget package places ABP client side scripts in "~/Abp/..." folder.

**Comment by Ivangrasp** [comment]
Yes, I'm updating my project to the last version of the template. 

Thanks!

**Comment by ismcagdas** [comment]
@Ivangrasp please reopen if this hasn't been fixed in the latest version.
