### ISSUE TITLE
Duplicate [GetAll] JaveScript in Layout

### ISSUE THREAD

**Issue by Tobyee** [aspnetboilerplate/module-zero-template#12]
````html
<script src="~/api/AbpServiceProxies/GetAll"></script>
<script src="~/api/AbpServiceProxies/GetAll?type=angular"></script>
````

[click to view](https://github.com/aspnetboilerplate/module-zero-template/blob/master/src/AbpCompanyName.AbpProjectName.WebSpaAngular/App/Main/views/layout/layout.cshtml#L37-L38)

**Comment by hikalkan** [comment]
I know. One for angularjs, one for jQuery.

**Comment by Tobyee** [comment]
@hikalkan you mean it's by designed?
Comparing to `aspnetboilerplate-templates` project, It's not duplicate.
https://github.com/aspnetboilerplate/aspnetboilerplate-templates/blob/master/src/AbpCompanyName.AbpProjectName.WebSpaAngular/App/Main/views/layout/layout.cshtml#L37

**Comment by hikalkan** [comment]
I know. Normally, no need to the jquery version in an angular project. But it helps us to call app services from browser console (example: http://www.aspnetzero.com/Documents/Developing-Step-By-Step#testing-personappservice-from-browser-console). Don't mind it. You can delete if you don't test like that.
