### ISSUE TITLE
aspnetboilerplate.com/Templates/CreateProject : Server Error

### ISSUE THREAD

**Issue by vicenteyu** [aspnetboilerplate/module-zero-template#123]
502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

**Comment by ismcagdas** [comment]
@vicenteyu it should be fixed now. Can you check again ?

**Comment by vicenteyu** [comment]
it's working fine. Thanks.
