### ISSUE TITLE
Nuget package warnings

### ISSUE THREAD

**Issue by ismcagdas** [aspnetboilerplate/module-zero-template#126]
Moved from https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3345

**Comment by ismcagdas** [comment]
@alirizaadiyahsi could you check it those warnings still exist ?

**Comment by alirizaadiyahsi** [comment]
Fixed by https://github.com/aspnetboilerplate/module-zero-template/commit/5e3366563cd3992107b7d21ed64347dcfde42898
