### ISSUE TITLE
serializeFormToObject plugin for jQuery has an issue with multiple inputs with the same name

### ISSUE THREAD

**Issue by gpcaretti** [aspnetboilerplate/module-zero-template#127]
When a form has multiple inputs with the same name (e.g. a group of checkboxes with the same name), 
the serializeFormToObject plugin in [main.js](https://github.com/aspnetboilerplate/module-zero-template/blob/master/src/AbpCompanyName.AbpProjectName.WebMpa/js/main.js) saves just the last input value.

Here a fix that store multiple values into a inner array.

```javascript
//serializeFormToObject plugin for jQuery
$.fn.serializeFormToObject = function () {
	//serialize to array
	var data = $(this).serializeArray();

	//add also disabled items
	$(':disabled[name]', this).each(function () {
		data.push({ name: this.name, value: $(this).val() });
	});

	//map to object preserving multiple inputs with the same name
	var obj = {};
	data.map(function (x) {
		if (obj.hasOwnProperty(x.name)) {
			if (!$.isArray(obj[x.name])) obj[x.name] = [obj[x.name]]; 
			obj[x.name].push(x.value);
		} else {
			obj[x.name] = x.value;
		}
	});

	return obj;
};
```

**Comment by ismcagdas** [comment]
@gpcaretti we have replaced this function with https://github.com/marioizquierdo/jquery.serializeJSON in AspNet Zero. I think it might work better for you as well. Could you give it a try ?

We can use this library in module-zero-template as well.
