### ISSUE TITLE
Creating a new role throws exception

### ISSUE THREAD

**Issue by ismcagdas** [aspnetboilerplate/module-zero-template#129]
Moved from https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3413#issuecomment-391647051.

**Comment by ismcagdas** [comment]
comments from @sajasbana:

@ismcagdas thanks for your considration i will use save changes for now
I want to share some notes  I saw:
- in v3.5 and before its working ... from v3.6 i saw this issue
- i made test in the test module v3.6 and it works ... thats weird i share it maybe you find it helpful (see attachment you can add to the project and see results)
- maybe some changes made this issue.

[Roles.zip](https://github.com/aspnetboilerplate/aspnetboilerplate/files/2038930/Roles.zip)

**Comment by may6288** [comment]
my english is very bad, you can try this:

public override async Task<RoleDto> Create(CreateRoleDto input)
{
            CheckCreatePermission();

            var role = ObjectMapper.Map<Role>(input);

            CheckErrors(await _roleManager.CreateAsync(role));

            var grantedPermissions = PermissionManager
                .GetAllPermissions()
                .Where(p => input.Permissions.Contains(p.Name))
                .ToList();

           //add this line
           **_await CurrentUnitOfWork.SaveChangesAsync();** 

            await _roleManager.SetGrantedPermissionsAsync(role, grantedPermissions);
            return MapToEntityDto(role);
        }

**Comment by ismcagdas** [comment]
@may6288 Thank you, we will do it like that.
