### ISSUE TITLE
initial migration issue

### ISSUE THREAD

**Issue by lkfortech** [aspnetboilerplate/module-zero-template#150]
hi,
i'm trying to "Update-Database" through package manager console but got error "A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"

please tell me where set connection string

**Comment by alirizaadiyahsi** [comment]
This issue is not related with module-zero-template.

You can change it in here: https://github.com/aspnetboilerplate/module-zero-template/blob/master/src/AbpCompanyName.AbpProjectName.WebMpa/Web.config#L24

**Comment by lkfortech** [comment]
Hello,


What is admin password?


<http://www.iqtcdigital.com>

________________________________

**Comment by alirizaadiyahsi** [comment]
admin/123qwe

https://aspnetboilerplate.com/Pages/Documents/Zero/Startup-Template

![image](https://user-images.githubusercontent.com/4375000/49866622-55af7600-fe19-11e8-8b14-d55241d15f5d.png)
