### ISSUE TITLE
Broken references etc.

### ISSUE THREAD

**Issue by Woodag** [aspnetboilerplate/module-zero-template#151]
![image](https://user-images.githubusercontent.com/33073255/51381896-9fc10100-1b15-11e9-81d7-efc30387f4d6.png)

**Comment by Woodag** [comment]
Probably someone remove nugets from packages.config but not from csproj file

**Comment by alirizaadiyahsi** [comment]
https://github.com/aspnetboilerplate/module-zero-template/commit/8240586aa32ab8c9f02ebdfde910ba38b16b0f7d

**Comment by alirizaadiyahsi** [comment]
Which project do you see this warnings? I mean which project did you get following screenshot?:

![image](https://user-images.githubusercontent.com/4375000/51466225-bcaa3e00-1d7a-11e9-99d2-c4f685725765.png)

I can't see any warning.

**Comment by Woodag** [comment]
Ok i download whole repository and rebuild 
![image](https://user-images.githubusercontent.com/33073255/51466868-77cadb00-1d6b-11e9-9bb0-77790f5434f0.png)

**Comment by alirizaadiyahsi** [comment]
When download from master branch, yes it seems problem still exist. Let me check this issue again. Thanks for feedback.

**Comment by ismcagdas** [comment]
As far as I remember, we have removed social logins from this template. If so, we can delete related OWIN packages.

**Comment by alirizaadiyahsi** [comment]
I deleted unused packages. I downloaded and tested with no warnings. Could you check? Before build, first clean.

**Comment by Woodag** [comment]
super thanks a lot
