### ISSUE TITLE
Change password modal

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero-template#16]

**Comment by ddNils** [comment]
I already did that, will provide pull request (until weekend)

**Comment by hikalkan** [comment]
Thank you, it's very appriciated :)

**Comment by ddNils** [comment]
I would like to propose the use of a dialog for password change - I used this approach: http://www.codeproject.com/Tips/826002/Bootstrap-Modal-Dialog-Loading-Content-from-MVC-Pa
