### ISSUE TITLE
System.Runtime reference in .Tests project

### ISSUE THREAD

**Issue by easyest** [aspnetboilerplate/module-zero-template#20]
Could You please remove that - the solution does not compile in VS2013. It could be related to [this issue] (https://github.com/dotnet/roslyn/issues/3362)

**Comment by hikalkan** [comment]
I can build in VS 2013. We upgraded template to .NET Framework 4.5.2. Do you have .NET 4.5.2 installed?

**Comment by easyest** [comment]
`System.Runtime` reference in `Tests` project is for specific version 4.0.0.0, but version 4.0.0.0 is already automatically referenced by VS because of some nuget package (or at least I think so) requirements, so VS gives an error:
>Error	2	An assembly with the same identity 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported. Try removing one of the duplicate references.

As `System.Runtime` is already included by VS, because it is required by another references in `Tests` project there is no need to specify this reference explicitly and VS will use the same version as `Core` or any other projects are using.
Another solution would be to set reference's `Specific Version` to `False`.
