### ISSUE TITLE
There are more than one source with name: AbpProjectName! Source name must be unique!

### ISSUE THREAD

**Issue by inernoro** [aspnetboilerplate/module-zero-template#23]
Migration database running error：
"There are more than one source with name: AbpProjectName! Source name must be unique!"
in "AbpCompanyName.AbpProjectName.WebMpa" and 

"AbpCompanyName.AbpProjectName.WebSpaDurandal"

**Comment by hikalkan** [comment]
Are you getting this error while running "Update-Database" command?

**Comment by hikalkan** [comment]
OK, I found the reason and will fix it soon.
Actually, they are not tested since not published. Current template only supports SPA angular. I started to develop MPA. Durandal will be dropped.

**Comment by oscarzaky** [comment]
I'm getting this error where it shows the source on D:\hilal while I don't even have the D: drive. Please help.
Running latest version of ABP 1.4.2

[AbpException: There are more than one source with name: Source! Source name must be unique!]
   Abp.Localization.LocalizationManager.InitializeSources() in D:\Halil\Github\aspnetboilerplate\src\Abp\Localization\LocalizationManager.cs:55
   Abp.AbpKernelModule.PostInitialize() in D:\Halil\Github\aspnetboilerplate\src\Abp\AbpKernelModule.cs:76
   Abp.Modules.<>c.<StartModules>b__15_2(AbpModuleInfo module) in D:\Halil\Github\aspnetboilerplate\src\Abp\Modules\AbpModuleManager.cs:48
   System.Collections.Generic.List`1.ForEach(Action`1 action) +85
   Abp.Modules.AbpModuleManager.StartModules() in D:\Halil\Github\aspnetboilerplate\src\Abp\Modules\AbpModuleManager.cs:48
   Abp.AbpBootstrapper.Initialize() in D:\Halil\Github\aspnetboilerplate\src\Abp\AbpBootstrapper.cs:137
   Abp.Web.AbpWebApplication`1.Application_Start(Object sender, EventArgs e) in D:\Halil\Github\aspnetboilerplate\src\Abp.Web\Web\AbpWebApplication.cs:29
   Efc.Web.MvcApplication.Application_Start(Object sender, EventArgs e) in C:\Projects\EthnicFoodCorner\V0.4.3\Efc.Web\Global.asax.cs:16

[HttpException (0x80004005): There are more than one source with name: Source! Source name must be unique!]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +9982013
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +118
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +336
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): There are more than one source with name: Source! Source name must be unique!]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9963380
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254

**Comment by hikalkan** [comment]
D:\Halil is just the path the dll is compiled. Don't care about it.
Do you have more than one localization sources? How this exception occured? Does it occur when you first create startup template? Or did you make some change, then error occured?

**Comment by oscarzaky** [comment]
I think I have multiple blocks in the project Core\ProjectCoreModule.cs
`
            //Add/remove localization sources here
            Configuration.Localization.Sources.Add(
                new DictionaryBasedLocalizationSource(
                    EfcConsts.LocalizationSourceName,
                    new XmlEmbeddedFileLocalizationDictionaryProvider(
                        Assembly.GetExecutingAssembly(),
                        "NobleSmart.Project.Localization.Source"
                        )
                    )
                );`

When I remove them, the error is gone but I got different error:

No language defined in this application.

Where do I define the default language?

**Comment by hikalkan** [comment]
Have you used "update-database" to fill abplanguages table in database (please check the table)
