### ISSUE TITLE
Local web sites interfere each other

### ISSUE THREAD

**Issue by kayagultekin** [aspnetboilerplate/module-zero-template#28]
I have generated 2 web sites from [http://www.aspnetboilerplate.com/Templates](http://www.aspnetboilerplate.com/Templates) and named them ZeroMPA the other is ZeroSPA. Then I set them up locally under Windows 10, IIS 10, App Pool Identity is used for Authentication at IIS.  They use localhost ports 55 and 56 respectively. I ran `Update-Database` command and published them to local folders.

and navigated to the web sites here is what happened:
- While I am logged in ZeroMPA as the default admin user, If I log in to ZeroSPA then I am logged out from ZeroMPA and vice versa
- Changing one of the web site's language changes the language of the other.

I am unsure whether this is or should be the expected behaviour and wanted to inform.

**Comment by hikalkan** [comment]
Normally, IIS should not share cookies between different applications/ports.
Did you created virtual directories or different applications?

**Comment by kayagultekin** [comment]
I created using "Add Web Site" as IIS call it, **not** by using "Add Virtual Directory". Indeed there is no such option when I right click on "Sites" and my web sites run under seperate app pools.

**Comment by hikalkan** [comment]
Strange.. we will test it soon. Thanks.

**Comment by kayagultekin** [comment]
I'd better close this because I see that this issue already discussed at several places and deducing that the port is not enough to seperate the cookies of two applications but giving custom names to the cookies is enough..
