### ISSUE TITLE
Implement the MPA template.

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero-template#3]

**Comment by rqx110** [comment]
waiting for this template!

**Comment by hikalkan** [comment]
Hi,

If you should start a new project and waiting for this template, please use plain ABP template and adapt module-zero as described here: http://www.aspnetboilerplate.com/Pages/Documents/Zero/Installation#DocInstallManual
Because it will take some time to create the template.

Thanks.

**Comment by Farb** [comment]
Like this

**Comment by GuilhermeMorais** [comment]
I Like this too! following the link now!

**Comment by scorpion86** [comment]
Waiting for this template.

**Comment by hikalkan** [comment]
It's finished. Planned to release tomorrow.

**Comment by scorpion86** [comment]
Thx so much 😀

**Comment by winsonet** [comment]
Is the multi page template is finished? but where can I find it?

thx~~

**Comment by hikalkan** [comment]
http://www.aspnetboilerplate.com/Templates

select "Multi Page Web Application" and check "Include module-zero"
