### ISSUE TITLE
how get HttpResponseMessage from MyAppService?

### ISSUE THREAD

**Issue by mona6767** [aspnetboilerplate/module-zero-template#4]
hi,best regard .

i want make  "public HttpResponseMessage GetImage()" in homeController , for get Files or JavascripFile ,
but when use "ControllerBase" , convert all response to "AjaxResponse" and not work for get files !!

please help me , how get Files HttpResponse , in my controller OR MyAppService ?

----
like your template in : 
"demo.aspnetzero.com/Profile/ChangeProfilePicture" 
and 
"demo.aspnetzero.com/Profile/GetProfilePicture?t=946464654"

VeryVery Thankyou.

**Comment by hikalkan** [comment]
Hi,

Have you tried to make return value of GetImage to ActionResult or FileResult?

**Comment by mona6767** [comment]
i want return value of Image and file (file like : javascript , or text files ! )

i can call normal (don't call it via AJAX) , from controller angular, in my view ?

**Comment by hikalkan** [comment]
ABP does not convert all controller results to AjaxResponse. Just actions returning JSonResult and called via AJAX. Can you share your action, so I can try it in my own environment.

**Comment by mona6767** [comment]
The problem was solved, thanks.

thank you .
