### ISSUE TITLE
Error start from empty

### ISSUE THREAD

**Issue by andmattia** [aspnetboilerplate/module-zero-template#48]
Last week I download a new version of ASPZero and after do update database I need create 6 row on tenants because I catch en error "PK_ tenants ID = 7"

**Comment by hikalkan** [comment]
You mean you downloaded from aspnetzero.com ?
If so, please write yo aspnet zero repository's issues.

**Comment by andmattia** [comment]
so sorry. 

The answer is yes

**Comment by hikalkan** [comment]
Thanks for moving it.
