### ISSUE TITLE
Error Join LINQ

### ISSUE THREAD

**Issue by andmattia** [aspnetboilerplate/module-zero-template#49]
`ERROR 2016-06-22 14:29:38,964 [8    ] lers.Filters.AbpExceptionFilterAttribute - The specified LINQ expression contains references to queries that are associated with different contexts.
System.NotSupportedException: The specified LINQ expression contains references to queries that are associated with different contexts.
   at System.Data.Entity.Core.Objects.ELinq.Funcletizer.FuncletizingVisitor.InlineObjectQuery(ObjectQuery inlineQuery, Type expressionType)
   at System.Data.Entity.Core.Objects.ELinq.Funcletizer.FuncletizingVisitor.InlineValue(Expression expression, Boolean recompileOnChange)
`
I'm getting this error if I join User with my table.
Configuration is 
- no multi tenant
- new project ASPnetzero

I try to update my project but it's broken and I need to rollback

**Comment by hikalkan** [comment]
Which version of Abp.* packages you are using?

**Comment by andmattia** [comment]
<package id="Abp" version="0.9.1.0" targetFramework="net461" />
  <package id="Abp.AutoMapper" version="0.9.1.0" targetFramework="net461" />
  <package id="Abp.Zero" version="0.9.1.0" targetFramework="net461" />
  <package id="Abp.Zero.Ldap" version="0.9.1.0" targetFramework="net461" />
  <package id="AutoMapper" version="3.3.1" targetFramework="net461" />
  <package id="Castle.Core" version="3.3.3" targetFramework="net451" />
  <package id="Castle.LoggingFacility" version="3.3.0" targetFramework="net451" />
  <package id="Castle.Windsor" version="3.3.0" targetFramework="net451" />
  <package id="Microsoft.AspNet.Identity.Core" version="2.2.1" targetFramework="net451" />
  <package id="Newtonsoft.Json" version="8.0.3" targetFramework="net461" />
  <package id="Nito.AsyncEx" version="3.0.1" targetFramework="net451" />
  <package id="System.Collections.Immutable" version="1.1.36" targetFramework="net461" />

**Comment by hikalkan** [comment]
You should upgrade to latest version since there was a bug in b0.9.1.
There is no breaking change to upgrade v0.9.6..
