### ISSUE TITLE
Social Media login support

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero-template#5]

**Comment by mohammad-shadmehr** [comment]
@hikalkan is the Twitter login an option? I have ver 6.4 of the ASPNETZERO (Angular project) and it does not have it!

**Comment by maliming** [comment]
@mohammad-shadmehr 

ASP.NET Core & Angular:  OK (**Facebook, Google**)
please refer: https://docs.aspnetzero.com/documents/common/latest/Version-Differences


Feature | ASP.NET Core & Angular | ASP.NET Core & JQuery | ASP.NET MVC 5.x & Angularjs | ASP.NET MVC 5.x & JQuery
-- | -- | -- | -- | --
Social Logins (Facebook, Twitter, Microsoft, Google+) | OK (Facebook, Google) | OK (all) | OK (all) | OK (all)
