### ISSUE TITLE
Create a module-zero-core-template

### ISSUE THREAD

**Issue by arthurspa** [aspnetboilerplate/module-zero-template#54]
Hey!

Considering that current version of `Abp.EntityFrameworkCore` has some [missing points ](http://www.aspnetboilerplate.com/Pages/Documents/Entity-Framework-Core#missing-points) like **Data Filters** and **Time Normalization**, **would I find some incompatibly** if I try to clone `aspnet-core-template` and from it create a `module-zero-core-template` by porting code form the current `module-zero-template`. 

If there is no **known** obstacle, I'll start porting it and share with **ABP** project.

**Comment by hikalkan** [comment]
Actually, this is what we planned to do. So, there should be no problem. But we don't think to use EF Core in module-zero-core-template since it has problems with data filters and that effects multi-tenancy and soft deletes.

**Comment by arthurspa** [comment]
Hey, again!

I'm trying to create a version of `module-zero-core-template` by porting code from  `module-zero-template` and integrating into `aspnet-core-template`. 

I'm having some issues because `module-zero-template` used `App.config` and `Web.config` for EF6 commands to work and get connection strings. In `module-zero-template` everything should be handled in code.

Do you have already an idea on how to integrate EF6 with ABP Core?

Note: tried [this](https://docs.asp.net/en/latest/data/entity-framework-6.html) article, but it didn't work (got exception when running `EntityFramework\Enable-Migrations` in Package Manager Console).

**Comment by hikalkan** [comment]
I suggest you to start from aspnet-core-template and then integrate module-zero, because solution structure is very different. New solution uses project.json/xproj approach while other uses classic csproj format.

I already integrated EF6 starting from the aspnet-core-template. I also could not used Package Manager Console commands and uses a library to make it work on command line: https://github.com/mrahhal/Migrator.EF6
Also, changed migrations a bit to make it working.

**Comment by arthurspa** [comment]
Thanks for the suggestions. 

Could you share your integration, if is not ask much? I didn't see any public branch with it and I suppose you'll  make it public. 

Thank you very much!

**Comment by hikalkan** [comment]
Hi,

Actually, AspNet Zero is a commerical product :) We will release it in the next week, then we planned to create module-zero-template for aspnet core. We think it will be available in 2 weeks.

**Comment by arthurspa** [comment]
Oh, I'm sorry. I know aspnet zero is a commercial product, I just didn't pay attention that you were referring to it. 

But it's good news that we will  get an integration soon! 

Thanks.

**Comment by hikalkan** [comment]
https://github.com/aspnetboilerplate/module-zero-core-template
