### ISSUE TITLE
Allow public browsing of web site

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero-template#56]
see https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1237

**Comment by gpcaretti** [comment]
Thanks for your reply.
I forgot to mention I commented out the part of header.cshtml/js about displaying name. So the issue is not there. My sensation is that the error is on the server side.

I right now investigate what you mean when writes "modify session service to handle it"
Tnx
gp

**Comment by gpcaretti** [comment]
See my pull for solving this point:
https://github.com/aspnetboilerplate/module-zero-template/pull/57
