### ISSUE TITLE
[dbo].[AbpUserClaims] not changing schema

### ISSUE THREAD

**Issue by diegosword** [aspnetboilerplate/module-zero-template#69]
I used this snippet      `modelBuilder.ChangeAbpTablePrefix<Tenant, Role, User>("", "NewSchemaName");`  to change the default schema for the ABP tables in a sql database. I works in all ABP tables but one  AbpUserClaims.  Any idea why?

**Comment by hikalkan** [comment]
see https://github.com/aspnetboilerplate/module-zero/issues/256
