### ISSUE TITLE
Abp redirects if credentials are wrongly entered in Login Page

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero-template#91]
see https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2011

**Comment by alirizaadiyahsi** [comment]
There may be some another reason for this. I you answer the following question, we can fix if there is an issue.

First, could you share your logs from Logs.txt?
And how it works when you use default alert lib sweet alert? Is it giving the same error?
Also could you share your custom codes that you change default alert lib?
