### ISSUE TITLE
Upgrade To Abp 2.1.1 Error

### ISSUE THREAD

**Issue by ghost** [aspnetboilerplate/module-zero-template#93]
in PermissionChecker return error to PermissionChecker<Tenant, Role, User>

````C#
namespace Chabok.Authorization
{
    public class PermissionChecker : PermissionChecker<Tenant, Role, User>
    {
        public PermissionChecker(UserManager userManager)
            : base(userManager)
        {

        }
    }
}
````

i remove Tenant and run it, but it's true???

**Comment by acjh** [comment]
Yes, it's a breaking change from [v2.1.0](https://github.com/aspnetboilerplate/module-zero/releases/tag/v2.1.0): aspnetboilerplate/module-zero#380

**Comment by AEChabok** [comment]
thanks

**Comment by gpcaretti** [comment]
Is it the unique change to apply? Does the database structure change? Something else?

**Comment by hikalkan** [comment]
see https://github.com/aspnetboilerplate/module-zero/releases/tag/v2.1.0
It does not effect db.
