### ISSUE TITLE
Convert to BSB admin theme like module-zero-core-template

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero-template#94]
Just like https://github.com/aspnetboilerplate/module-zero-core-template

**Comment by natiki** [comment]
Hi Halil,

While you are in there cleaning up the template you may want to check it for missing CSS classes and other code optomisations. This from Login.cshtml but I see most of the cshtml has the same kinds of issues (ie missing CSS classes and so on).

![image](https://user-images.githubusercontent.com/4738140/27685979-f4ab3120-5d13-11e7-8bd8-42acb898a530.png)

**Comment by hikalkan** [comment]
Thanks for pointing this.
