### ISSUE TITLE
Test social logins

### ISSUE THREAD

**Issue by ismcagdas** [aspnetboilerplate/module-zero-template#95]
See https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2362

**Comment by ellaisys** [comment]
ok thank you.

**Comment by ellaisys** [comment]
Any updates on this issue? I am still having problems with Facebook logins as mentioned in aspnetboilerplate/aspnetboilerplate#2362

**Comment by ismcagdas** [comment]
Hi @ellaisys,

We didn't test it yet but we will in a short time.
