### ISSUE TITLE
Template generation fails when click on "Create My Project"

### ISSUE THREAD

**Issue by gpcaretti** [aspnetboilerplate/module-zero-template#96]
* Module zero templete release 2.1.1
* ASP.NET MVC 5
* AngularJS + EF

When you press "Create My Project", it fails. See attached.

I also tried with ASP.NET Core 1.x. In that case it hangs.

![capture](https://user-images.githubusercontent.com/5499871/29061782-84e80202-7c1f-11e7-9999-27aed19a5658.PNG)
image

**Comment by hikalkan** [comment]
We are currently fixing it.

**Comment by hikalkan** [comment]
Please follow https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2401
