### ISSUE TITLE
Culture Issue for Vietnamese

### ISSUE THREAD

**Issue by rqx110** [aspnetboilerplate/module-zero-template#98]
https://github.com/aspnetboilerplate/module-zero-template/blob/a270c870a7f0fb3dac3b24f693a4fa6da68a40a8/src/AbpCompanyName.AbpProjectName.EntityFramework/Migrations/SeedData/DefaultLanguagesCreator.cs#L28,  should be `new ApplicationLanguage(null, "vi", "Vietnamese", "famfamfam-flags vn")`
see the issue :[https://stackoverflow.com/questions/45752656/asp-net-boilerplate-startup-template-culture-issue]( https://stackoverflow.com/questions/45752656/asp-net-boilerplate-startup-template-culture-issue)

**Comment by ismcagdas** [comment]
Thanks @rqx11, we will fix this.
